version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=exoplanet-data
    networks:
      - marvel

  exoplanet_apis:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: exoplanet_apis
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - marvel

networks:
  marvel: